### PR TITLE
Fix tests to pass with both new and old DateTime::Locale versions

### PR DESCRIPTION
**Pull request by autarch**

### CODE REVIEW

**Comment by autarch** [comment]
ping

**Comment by autarch** [comment]
I'm going to release a new DateTime::Locale today, which will break this module.

**Comment by abraxxa** [comment]
I'd need a fixed release of this module. Is there anything missing to apply this patch and release a new version to CPAN?

**Comment by ilmari** [comment]
The patch in #2 is also needed, since the type constraint won't accept the new objects.

@tobyink: if you don't have the time to maintain this module, could you give comaint to e.g. @autarch, so he can keep it up to date when things change in DateTime?

**Pull request merged**
